### ISSUE TITLE
Problems installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by DerekMcKay** [sabourke/lofarstationdata#4]
I have been trying to install this on Ubuntu 16.04 with no success. I've have carefully followed the instructions in the readme and as indicated here on GitHub. The following is my setup and installation.

PART 1 -- ENVIRONMENT
----------------------------------

I have a moderately new (Feb 2017) installation of Ubuntu 16.04. Specifically:

    computer platform = Linux-4.4.0-75-generic-x86_64-with-Ubuntu-16.04-xenial
    python version = 2.7.12
    numpy version = 1.12.1
    scipy version = 0.19.0
    (py)ephem version = 3.7.6.0
    matplotlib version = 2.0.0
    h5py version = 2.6.0
    PIL version = 1.1.7

PART 2 -- INSTALLATION
---------------------------------

The following are my installation steps. Python 2.7 (incl. numpy, scipy, etc.) were already installed as indicated above.

sudo apt-get install software-properties-common
sudo add-apt-repository ppa:kernsuite/kern-1
sudo apt-add-repository multiverse
sudo apt-add-repository restricted
sudo apt-get update
sudo apt-get install python-casacore
sudo -H pip install git+https://github.com/sabourke/lofarstationdata

All of these ran without any indication of error.

PART 3 -- TESTING
--------------------------

First I check that the executable is present.

%  which  lofar-station-ms
/usr/local/bin/lofar-station-ms

Then I try running the "help" option, as indicated in the documentation. This is where it starts to fail.

%  lofar-station-ms --help
Traceback (most recent call last):
  File "/usr/local/bin/lofar-station-ms", line 9, in <module>
    load_entry_point('lofarstationdata==0.8', 'console_scripts', 'lofar-station-ms')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/lofarstation/converter.py", line 5, in <module>
    from casacore.measures import measures
  File "/usr/lib/python2.7/dist-packages/casacore/measures/__init__.py", line 30, in <module>
    import casacore.quanta as dq
  File "/usr/lib/python2.7/dist-packages/casacore/quanta/__init__.py", line 1, in <module>
    from .quantity import quantity, is_quantity
  File "/usr/lib/python2.7/dist-packages/casacore/quanta/quantity.py", line 2, in <module>
    from ._quanta import Quantity
ImportError: /usr/lib/python2.7/dist-packages/casacore/quanta/_quanta.x86_64-linux-gnu.so: undefined symbol: _ZN4casa16throwArrayShapesERKNS_9IPositionES2_PKc

PART 4 -- HELP?
----------------------

Any suggestions on additional packages that might be needed or any configurations steps that could tried? If possible, could these be added to (or clarified in) the documentation. Thanks.

**Comment by sabourke** [comment]
I'm not able to reproduce the error - when I do the step above there is no problem. From the error it looks like the problem is a binary incompatibility within python-casacore or between casacore and python-casacore. Do you have multiple casacore's installed? Installing python-casacore from kern would have pulled in the kern version of casacore too...

**Comment by sabourke** [comment]
I looked into this a bit more and my guess is that kern-1 and kern-2 packages have been intermixed on your machine and your python-casacore is currently broken (you can test this with "import casacore.quanta" from within python).
The symbol that causing the issue above is not needed in the kern-1 version of python-casacore nor provided by the kern-1 version of libcasa_casa.so.2.1.0  It is however required by kern-2 python-casacore and provided by kern-2 libcasa_casa.so.2.2.0

If you want to move to kern-2. The following _might_ work:
```
add-apt-repository -r ppa:kernsuite/kern-1
add-apt-repository ppa:kernsuite/kern-2
apt-get update
apt-get dist-upgrade
```

**Comment by sabourke** [comment]
lofarstationdata doesn't need kern-2 by the way the versions in kern-1 would be fine too. You just can't mix them.

**Comment by DerekMcKay** [comment]
I believe your hypothesis regarding the kern-1/kern-2 intermixing is correct. I've run the suggested "apt" commands you made and the "import casacore.quanta" and "lofar-station-ms -h" tests are now working. My guess is that this has resolved the problem, so I will close this issue now and press on. Many thanks for your prompt and accurate support. It was much appreciated!
